#!/usr/bin/python
import sys, json, requests
url = 'https://www.maxmind.com/geoip/v2.1/city/%%?use-downloadable-db=1&demo=1'
for ip in sys.argv[1:]:
    request = requests.get(url.replace('%%', ip))
    response = json.loads(request.text)
    print '-' * 25
    print 'ip: ' + ip
    if 'traits' in response:
        if 'organization' in response['traits']:
            print 'org: ' + response['traits']['organization']
        if 'isp' in response['traits']:
            print 'isp: ' + response['traits']['isp']
    if 'subdivisions' in response:
        print 'state: ' + response['subdivisions'][0]['names']['en']
    if 'country' in response:
        print 'country: ' + response['country']['names']['en']
    if 'tz' in response:
        print 'tz: ' + response['location']['time_zone']
    if 'postal' in response:
        print 'zip: ' + response['postal']['code']
